# Generated by Django 3.0.3 on 2020-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('current_city', models.CharField(max_length=200)),
                ('neighbour_hood', models.CharField(max_length=200)),
                ('current_employment', models.CharField(max_length=1000)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField()),
                ('file_upload', models.FileField(upload_to='Applications/Files/%Y')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Job Applications Recieved',
            },
        ),
    ]
