# Generated by Django 3.0.3 on 2020-02-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
