# Generated by Django 3.0.3 on 2020-03-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery2',
            options={'verbose_name_plural': 'Extra Curricular Activities'},
        ),
    ]
