# Generated by Django 3.0.3 on 2020-03-04 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='Prospectus/%Y')),
                ('name', models.CharField(blank=True, max_length=5000)),
                ('description', models.TextField(blank=True)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Flyers',
            },
        ),
    ]
