# Generated by Django 3.0.3 on 2020-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Album Name')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
