# Generated by Django 3.0.3 on 2020-03-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.AddField(
            model_name='gallery',
            name='url_album',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
