# Generated by Django 3.0.3 on 2020-02-28 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Post/comments/%Y')),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Home Page',
            },
        ),
    ]
