# Generated by Django 3.0.3 on 2020-03-03 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('user_id', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
