# Generated by Django 3.0.3 on 2020-03-03 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.URLField(blank=True, max_length=20000)),
                ('twiter', models.URLField(blank=True, max_length=20000)),
                ('instagram', models.URLField(blank=True, max_length=20000)),
                ('google_plus', models.URLField(blank=True, max_length=20000)),
                ('linkedin', models.URLField(blank=True, max_length=20000)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000)),
                ('email', models.EmailField(blank=True, max_length=5000)),
                ('website', models.CharField(blank=True, max_length=5000)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog')),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
