# Generated by Django 3.0.3 on 2020-02-28 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000)),
                ('email', models.EmailField(blank=True, max_length=5000)),
                ('website', models.CharField(blank=True, max_length=5000)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Blog')),
            ],
            options={
                'ordering': ['comment_date'],
            },
        ),
    ]
