# Generated by Django 3.0.3 on 2020-02-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blog',
            name='facebook',
            field=models.URLField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='google_plus',
            field=models.URLField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='instagram',
            field=models.URLField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='linkedin',
            field=models.URLField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='blog',
            name='twiter',
            field=models.URLField(blank=True, max_length=20000),
        ),
    ]
