# Generated by Django 3.0.3 on 2020-03-05 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='Speach/%Y')),
                ('title', models.CharField(blank=True, max_length=5000)),
                ('name', models.CharField(blank=True, max_length=5000)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Speaches',
            },
        ),
    ]
