# Generated by Django 3.0.3 on 2020-02-29 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=5000)),
                ('name', models.CharField(blank=True, max_length=10000)),
                ('description', models.TextField(blank=True)),
                ('date_issued', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Rules and Regulations',
            },
        ),
    ]
