# Generated by Django 3.0.3 on 2020-03-04 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500)),
                ('author_title', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(max_length=200)),
                ('sub_topic', models.CharField(blank=True, max_length=300)),
                ('crew', models.CharField(blank=True, max_length=5000, verbose_name='Available Teachers')),
                ('follow_up_by', models.CharField(blank=True, max_length=5000)),
                ('period_tought', models.CharField(blank=True, max_length=5000)),
                ('description', models.TextField()),
                ('downloadable', models.FileField(blank=True, null=True, upload_to='')),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Curriculum',
            },
        ),
    ]
