# Generated by Django 3.0.3 on 2020-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='edit_date',
            new_name='date_published',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='author',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='author_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
