# Generated by Django 3.0.3 on 2020-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20200303_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='possision',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='downloadable',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
