# Generated by Django 3.0.3 on 2020-03-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_auto_20200303_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='sub_topic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
